version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    automerge:
      enabled: true
      options:
        labels:
          - "dependencies"